# Generated by Django 4.2.10 on 2024-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To-Do'), ('PROG', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=4),
        ),
    ]
